// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4qCZqPYCQN4MrL9qCCq0goUwORgpQgIk',
    appId: '1:120228818733:web:58b6830372b3885be0ada4',
    messagingSenderId: '120228818733',
    projectId: 'jhatfatuser-ec040',
    authDomain: 'jhatfatuser-ec040.firebaseapp.com',
    databaseURL: 'https://jhatfatuser-ec040-default-rtdb.firebaseio.com',
    storageBucket: 'jhatfatuser-ec040.appspot.com',
    measurementId: 'G-P97QS92M23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZkyPDwxcdxRLwGBu5mKP8j4L1vJAqyTQ',
    appId: '1:120228818733:android:3715661bb2ddf7c0e0ada4',
    messagingSenderId: '120228818733',
    projectId: 'jhatfatuser-ec040',
    databaseURL: 'https://jhatfatuser-ec040-default-rtdb.firebaseio.com',
    storageBucket: 'jhatfatuser-ec040.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9uWf-xe37J2The54Ul0Hz6F0kcMVntfk',
    appId: '1:120228818733:ios:2b90443543c07b9be0ada4',
    messagingSenderId: '120228818733',
    projectId: 'jhatfatuser-ec040',
    databaseURL: 'https://jhatfatuser-ec040-default-rtdb.firebaseio.com',
    storageBucket: 'jhatfatuser-ec040.appspot.com',
    androidClientId: '120228818733-13k89fptgs6ht7upctuv3qj48jge8n84.apps.googleusercontent.com',
    iosClientId: '120228818733-877ti5fpiifgmo5hok8cph3vqdtc3hab.apps.googleusercontent.com',
    iosBundleId: 'com.jhatfat.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9uWf-xe37J2The54Ul0Hz6F0kcMVntfk',
    appId: '1:120228818733:ios:7e40fd5f5a7a5a5fe0ada4',
    messagingSenderId: '120228818733',
    projectId: 'jhatfatuser-ec040',
    databaseURL: 'https://jhatfatuser-ec040-default-rtdb.firebaseio.com',
    storageBucket: 'jhatfatuser-ec040.appspot.com',
    androidClientId: '120228818733-13k89fptgs6ht7upctuv3qj48jge8n84.apps.googleusercontent.com',
    iosClientId: '120228818733-5lrpl3o3h2u9144845q9597s2ghn42pr.apps.googleusercontent.com',
    iosBundleId: 'com.jhatfat.user.jhatfatdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4qCZqPYCQN4MrL9qCCq0goUwORgpQgIk',
    appId: '1:120228818733:web:5417f587e9b6f41ee0ada4',
    messagingSenderId: '120228818733',
    projectId: 'jhatfatuser-ec040',
    authDomain: 'jhatfatuser-ec040.firebaseapp.com',
    databaseURL: 'https://jhatfatuser-ec040-default-rtdb.firebaseio.com',
    storageBucket: 'jhatfatuser-ec040.appspot.com',
    measurementId: 'G-JXKSV2XR8Y',
  );
}
